---
- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/env python2"
  tasks:
  - name: Ensure Debian-like OS dependencies are installed
    apt: name={{ item }} state=latest
    with_items:
    - python3
    - python3-dev
    - python3-pip
    - python3.4-venv
    - python-virtualenv
    - libmysqlclient-dev
    - graphviz
    - libgraphviz-dev
    - pkg-config
    - screen
    - dnsmasq
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Ensure Archlinux dependencies are installed
    pacman: name={{ item }} state=latest
    with_items:
    - python-pip
    - python
    - python-virtualenv
    - libmysqlclient
    - graphviz
    - pkg-config
    - screen
    - dnsmasq
    when: ansible_distribution == 'Archlinux'

  - name: Install the raptiformica-map repository
    git: repo=https://github.com/vdloo/raptiformica-map.git
      dest=/usr/etc/raptiformica_map
      version=master
      force=yes
      update=yes
    register: raptiformica_map_git

  - name: Install raptiformica-map requirements in the virtualenv on Ubuntu
    pip:
      requirements=/usr/etc/raptiformica_map/requirements/base.txt
      virtualenv=/usr/etc/raptiformica_map/venv
      virtualenv_command=pyvenv-3.4
    when: ansible_distribution == 'Ubuntu'

  - name: Install raptiformica-map requirements in the virtualenv
    pip:
      requirements=/usr/etc/raptiformica_map/requirements/base.txt
      virtualenv=/usr/etc/raptiformica_map/venv
      virtualenv_python=python3
    when: ansible_distribution != 'Ubuntu'

  - name: Install pygraphviz for Ubuntu
    shell: >
      PYTHONPATH=/usr/etc/raptiformica_map/
      /usr/etc/raptiformica_map/venv/bin/pip3
      install pygraphviz==1.3.1
      --install-option="--include-path=/usr/include/graphviz"
      --install-option="--library-path=/usr/lib/graphviz/"
      --exists-action=w
    when: ansible_distribution == 'Ubuntu'

  - name: Install pygraphviz for everyone else
    shell: >
      PYTHONPATH=/usr/etc/raptiformica_map/
      /usr/etc/raptiformica_map/venv/bin/pip3
      install pygraphviz==1.3.1
      --exists-action=w
    when: ansible_distribution != 'Ubuntu'

  - name: Configure dnsmasq for consul
    lineinfile:
      dest: /etc/dnsmasq.d/10-consul
      line: server=/consul/127.0.0.1#8600
      state: present
      create: yes

  - name: Kill the service if it is running an old release
    # brackets so pkill does not terminate its own process
    shell: pkill -f [r]aptiformica_map || /bin/true

  # todo: refactor this to a supervisord script, not all hosts have an init system
  - name: Ensure the detached webservice is running
    shell: >
      screen -ls | grep -q raptiformica_map ||
      screen -S raptiformica_map -d -m
      bash -c 'PYTHONPATH=/usr/etc/raptiformica_map/
      /usr/etc/raptiformica_map/venv/bin/python3
      /usr/etc/raptiformica_map/raptiformica_map/web.py'

  # todo: refactor this to a supervisord script, not all hosts have an init system
  - name: Ensure detached dnsmasq is running
    shell: >
      screen -ls | grep -q dnsmasq ||
      screen -S dnsmasq -d -m
      /usr/sbin/dnsmasq --no-daemon
